// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:2369967c-f3b6-4cd6-bd43-dc8fa7fcc7e8",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_09hOaAK2Z",
    "aws_user_pools_web_client_id": "6cf7cnn2b6tnl6k2536plutl3g",
    "oauth": {}
};


export default awsmobile;
